### ISSUE TITLE
About the 56 animal categories

### ISSUE THREAD

**Issue by 2019EPWL** [llorz/3DV22_DeformingThings4DMatching_dataset#1]
Hi, thank you for your excellent work. In the paper,  "We select 56 animal categories and 8 humanoid categories from DEFORMTHINGS4D."  However,  I only can find the 9 humanoid categories except the 56 animal categories in this repo.

**Comment by llorz** [comment]
Hi, I just uploaded the remeshed animal shapes that were used in the paper. Hope this helps.
